#!/usr/bin/env bash
# Builds the session-title CLI bundle and installs it to a stable,
# checkout-independent location, plus a `lcars` launcher on PATH.
#
# Why this exists (issue #1212): the declared-title channel
# (`lcars session title "..."`, see the app README) and the host-side Codex
# native-title importer (agent-lcars-session-title-import.timer, see
# systemd/ in this directory) both need this CLI runnable by a stable name,
# but nothing installed it -- an agent could only run `lcars session title`
# if this exact build-and-copy sequence had already happened by hand. A
# perfectly wired watcher with nothing on PATH still ships zero declared
# titles.
#
# This also has to NOT point anything at the checkout's own `dist/`: the
# primary checkout (`~/p/agent-lcars` on a watcher host) is guardrail-
# reserved for a clean `main`, `git clean -xfd` there erases build
# artifacts outright, and docker-compose.yml's own preamble is explicit
# that watcher hosts "do not build application code during deployment" for
# the containerized daemon. That constraint is about the immutable image
# the compose stack pulls, not about this separate, non-containerized host
# tool -- but the spirit still applies: this script copies the built
# bundle OUT of the checkout into $LIB_DIR below, once, so neither the
# import timer nor an interactive `lcars` invocation depends on the
# checkout's working tree afterward.
#
# Usage: from a checkout of this repo on the watcher host (the primary
# ~/p/agent-lcars checkout that persists long-term, not a worktree meant to
# be torn down):
#   apps/telemetry-watcher/deploy/install-session-title-cli.sh
#
# Re-run after any change to the session-title CLI or its dependencies
# lands on that checkout's main -- this script does not watch for changes
# or run itself automatically.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
LIB_DIR="${AGENT_LCARS_SESSION_TITLE_CLI_LIB_DIR:-$HOME/.local/lib/agent-lcars}"
BIN_DIR="${AGENT_LCARS_SESSION_TITLE_CLI_BIN_DIR:-$HOME/.local/bin}"
BUNDLE_NAME=lcars-session-title.cjs
BUILT_BUNDLE="$REPO_ROOT/dist/apps/telemetry-watcher-session-title-cli/$BUNDLE_NAME"

cd "$REPO_ROOT"
./tools/nx run @agent-lcars/telemetry-watcher:session-title-cli

if [ ! -f "$BUILT_BUNDLE" ]; then
  echo "$BUILT_BUNDLE was not produced by the session-title-cli build -- check apps/telemetry-watcher/project.json's outputPath/outputFileName for that target." >&2
  exit 1
fi

mkdir -p "$LIB_DIR" "$BIN_DIR"
install -m 0644 "$BUILT_BUNDLE" "$LIB_DIR/$BUNDLE_NAME"

# The launcher is named `lcars`, not `lcars-session-title`: the command
# parser (session-title-annotation-command.ts) only ever inspects
# argv[0]/argv[1] for the literal strings "session"/"title" -- it never
# looks at its own binary name -- so naming the launcher `lcars` is what
# makes `lcars session title "..."` (the surface #1081 specified, and what
# the READMEs teach agents to run) the actual command typed, instead of the
# more awkward `lcars-session-title session title "..."`.
#
# Node resolution: this fleet's Node is fnm-managed, and fnm's shim lives
# in a per-shell `/run/user/<uid>/fnm_multishells/<pid>_<ts>/bin` directory
# that is not guaranteed to be on PATH for every caller of this launcher --
# an agent's own tool-call subprocess in particular often runs a bare
# non-login, non-interactive shell that never sourced the rc file that sets
# fnm's PATH up. Prefer a `node` already on PATH (covers a future/other
# host with a system package instead of fnm); otherwise fall back to fnm's
# `default` alias, a stable symlink (`fnm default <version>` sets it, not
# tied to any one shell's PID) pinned to this repo's `engines.node` major.
# The systemd import unit reuses this same launcher rather than
# re-implementing this resolution a second time.
cat >"$BIN_DIR/lcars" <<LAUNCHER
#!/bin/sh
# Generated by apps/telemetry-watcher/deploy/install-session-title-cli.sh --
# re-run that script to update this file. Do not edit by hand.
exec "\$(command -v node || echo "\$HOME/.local/share/fnm/aliases/default/bin/node")" \\
  "$LIB_DIR/$BUNDLE_NAME" "\$@"
LAUNCHER
chmod 0755 "$BIN_DIR/lcars"

echo "Installed $LIB_DIR/$BUNDLE_NAME and launcher $BIN_DIR/lcars"
if ! command -v lcars >/dev/null 2>&1; then
  echo "$BIN_DIR is not on this shell's PATH -- add it (e.g. in your shell rc) for 'lcars session title' to work interactively. The systemd import timer invokes $BIN_DIR/lcars by its full path and does not need PATH." >&2
fi
