// One scenario inventory for native execution and its release evidence consumer.
import { publicationDeliveryModes } from './publication-fixture.mjs';
import { reviewAcknowledgmentModes } from './review-fixture.mjs';

export function nativeModes(provider) {
  if (!['claude', 'codex', 'opencode'].includes(provider))
    throw new Error('Unknown provider');
  return provider === 'opencode' ? opencodeModes() : commandModes(provider);
}
export const setupModes = [
  'malformed-config',
  'symlink-config',
  'missing-setup',
];

function commandModes(provider) {
  return [
    'bootstrap-delegated-allow',
    'bootstrap-delegated-review',
    'bootstrap-workflow',
    'bootstrap-workflow-recovery',
    'bootstrap-workflow-recovery-exhausted',
    'bootstrap-workflow-correction',
    'bootstrap-workflow-exhausted',
    'allow',
    'deny',
    'failure',
    'missing',
    'bridge-allow',
    'bridge-failure',
    'bridge-timeout',
    'bridge-rewrite',
    'bridge-marker',
    'resume',
    'bootstrap-marker',
    'bridge-recovery-success',
    'bridge-recovery-failure',
    'bootstrap-file-allow',
    'bootstrap-file-primary',
    'bootstrap-file-symlink',
    'bootstrap-file-review',
    'bootstrap-file-ownership-absent',
    'bootstrap-file-ownership-unreadable',
    'bootstrap-file-ownership-changed',
    'bootstrap-file-session-expected-mismatch',
    'bootstrap-file-session-bound-mismatch',
    'bootstrap-hold-draft-blocked',
    'bootstrap-hold-draft-released',
    'bootstrap-hold-merge-blocked',
    'bootstrap-hold-merge-released',
    'bootstrap-hold-draft-threads',
    ...reviewAcknowledgmentModes,
    'bootstrap-outcome-park-allow',
    'bootstrap-outcome-no-op-allow',
    'bootstrap-outcome-foreign',
    'bootstrap-outcome-unrelated',
    'bootstrap-outcome-parent-symlink',
    ...(provider === 'codex' ? ['bootstrap-outcome-multi-target'] : []),
    ...publicationDeliveryModes,
    'bootstrap-publication-allow',
    'bootstrap-publication-review',
    'bootstrap-publication-ownership-absent',
    'bootstrap-publication-ownership-unreadable',
    'bootstrap-publication-ownership-changed',
    'bootstrap-publication-marker-idempotent-allow',
    'bootstrap-publication-marker-foreign',
    'bootstrap-push-allow',
    'bootstrap-push-review',
    'bootstrap-push-primary',
    'bootstrap-push-ownership-absent',
    'bootstrap-push-ownership-unreadable',
    'bootstrap-push-ownership-changed',
  ];
}

function opencodeModes() {
  return [
    'bootstrap-delegated-allow',
    'bootstrap-delegated-review',
    'bootstrap-workflow',
    'bootstrap-workflow-recovery',
    'bootstrap-workflow-recovery-exhausted',
    'bootstrap-workflow-correction',
    'bootstrap-workflow-exhausted',
    'allow',
    'deny',
    'failure',
    'missing',
    'policy-marker',
    'policy-deny',
    'policy-failure',
    'bootstrap-marker',
    'policy-recovery-success',
    'policy-recovery-exhausted',
    'policy-timeout-success',
    'policy-timeout-exhausted',
    'bootstrap-file-allow',
    'bootstrap-file-primary',
    'bootstrap-file-symlink',
    'bootstrap-file-review',
    'bootstrap-file-ownership-absent',
    'bootstrap-file-ownership-unreadable',
    'bootstrap-file-ownership-changed',
    'bootstrap-file-session-expected-mismatch',
    'bootstrap-file-session-bound-mismatch',
    'bootstrap-hold-draft-blocked',
    'bootstrap-hold-draft-released',
    'bootstrap-hold-merge-blocked',
    'bootstrap-hold-merge-released',
    'bootstrap-hold-draft-threads',
    ...reviewAcknowledgmentModes,
    'bootstrap-outcome-park-allow',
    'bootstrap-outcome-no-op-allow',
    'bootstrap-outcome-foreign',
    'bootstrap-outcome-unrelated',
    'bootstrap-outcome-parent-symlink',
    'bootstrap-lineage',
    'bootstrap-file-resume',
    'bootstrap-lineage-recovery-success',
    'bootstrap-lineage-recovery-exhausted',
    ...publicationDeliveryModes,
    'bootstrap-publication-allow',
    'bootstrap-publication-review',
    'bootstrap-publication-ownership-absent',
    'bootstrap-publication-ownership-unreadable',
    'bootstrap-publication-ownership-changed',
    'bootstrap-publication-marker-idempotent-allow',
    'bootstrap-publication-marker-foreign',
    'bootstrap-push-allow',
    'bootstrap-push-review',
    'bootstrap-push-primary',
    'bootstrap-push-ownership-absent',
    'bootstrap-push-ownership-unreadable',
    'bootstrap-push-ownership-changed',
  ];
}
