#!/bin/bash

set -e

export NX_TUI=false
export NX_DAEMON=false

./tools/require-feature-worktree.sh

./tools/check-dependencies.sh
./tools/nx format:check --base=origin/main
./tools/nx affected -t lint typecheck --base=origin/main
